### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by ghost** [DrZhark/mocreatures#111]
I did nothing else than just running around. I dont clicked on anything. Then my client chrashed (server still running) and I got the following crash report.

Running 1.12.2 with DrZharks MoCreatures Mod-12.0.5.jar
and NO CustomMobSpawner.
java 8.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  ForgelinPlugin (Forgelin-1.8.0.jar)
  OTGCorePlugin (OTG-Core.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.17.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 11/9/18 2:25 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:89)
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.func_70094_T(MoCEntityTameableAquatic.java:452)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:232)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
	at drzhark.mocreatures.entity.MoCEntityAquatic.func_70030_z(MoCEntityAquatic.java:914)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2089)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:89)
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.func_70094_T(MoCEntityTameableAquatic.java:452)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:232)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
	at drzhark.mocreatures.entity.MoCEntityAquatic.func_70030_z(MoCEntityAquatic.java:914)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2089)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: mocreatures:goldfish (drzhark.mocreatures.entity.aquatic.MoCEntityGoldFish)
	Entity ID: 7479
	Entity Name: GoldFish
	Entity's Exact location: -403.50, 63.00, -430.50
	Entity's Block location: World: (-404,63,-431), Chunk: (at 12,3,1 in -26,-27; contains blocks -416,0,-432 to -401,255,-417), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['XXXXXXXXXX'/1859, l='MpServer', x=-325.28, y=65.23, z=-452.54]]
	Chunk stats: MultiplayerChunkCache: 406, 406
	Level seed: 0
	Level generator: ID 09 - OTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-500,64,-706), Chunk: (at 12,4,14 in -32,-45; contains blocks -512,0,-720 to -497,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 18136 game time, 18136 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 105 total; [EntitySkeleton['Skeleton'/7429, l='MpServer', x=-316.50, y=72.00, z=-392.50], EntitySkeleton['Skeleton'/7435, l='MpServer', x=-381.47, y=43.00, z=-458.73], EntitySkeleton['Skeleton'/7436, l='MpServer', x=-382.50, y=38.00, z=-464.50], EntitySkeleton['Skeleton'/7437, l='MpServer', x=-381.50, y=38.00, z=-465.50], EntityCreeper['Creeper'/7439, l='MpServer', x=-245.50, y=70.00, z=-409.50], EntityCreeper['Creeper'/7440, l='MpServer', x=-259.50, y=43.00, z=-450.50], EntityCreeper['Creeper'/7441, l='MpServer', x=-259.50, y=43.00, z=-449.50], MoCEntityWerewolf['Werewolf'/7186, l='MpServer', x=-259.55, y=7.00, z=-503.45], EntityCreeper['Creeper'/7442, l='MpServer', x=-257.50, y=43.00, z=-452.50], MoCEntityBlackBear['BlackBear'/5397, l='MpServer', x=-316.50, y=75.00, z=-468.50], MoCEntityBlackBear['BlackBear'/5398, l='MpServer', x=-314.50, y=75.00, z=-469.50], MoCEntityBlackBear['BlackBear'/5399, l='MpServer', x=-317.50, y=75.00, z=-470.50], EntityCreeper['Creeper'/7456, l='MpServer', x=-384.50, y=72.00, z=-430.50], EntityZombie['Zombie'/7206, l='MpServer', x=-359.50, y=44.00, z=-444.50], EntitySkeleton['Skeleton'/7462, l='MpServer', x=-261.50, y=14.00, z=-472.50], EntitySkeleton['Skeleton'/7207, l='MpServer', x=-364.50, y=44.00, z=-440.50], EntityZombie['Zombie'/7464, l='MpServer', x=-250.50, y=67.00, z=-514.50], EntityEnderman['Enderman'/7209, l='MpServer', x=-356.50, y=26.00, z=-519.50], EntityCreeper['Creeper'/7466, l='MpServer', x=-248.50, y=67.00, z=-514.50], EntityBrainyZombie['Angry Zombie'/7467, l='MpServer', x=-277.50, y=27.00, z=-452.50], EntityItem['item.tile.mushroom.glowshroom'/7472, l='MpServer', x=-308.95, y=16.00, z=-438.24], EntityItem['item.tile.mushroom.glowshroom'/7473, l='MpServer', x=-309.88, y=16.00, z=-437.07], EntityItem['item.tile.flower_1.miners_delight'/7475, l='MpServer', x=-304.77, y=17.00, z=-434.83], EntityItem['item.tile.flower_1.miners_delight'/7476, l='MpServer', x=-309.88, y=16.00, z=-436.43], EntityCreeper['Creeper'/6965, l='MpServer', x=-307.50, y=73.00, z=-520.50], EntityItem['item.tile.flower_1.miners_delight'/7478, l='MpServer', x=-309.21, y=16.00, z=-437.87], MoCEntityGoldFish['GoldFish'/7479, l='MpServer', x=-403.50, y=63.00, z=-430.50], EntityItem['item.tile.flower_1.miners_delight'/6968, l='MpServer', x=-323.80, y=33.00, z=-470.78], MoCEntityGoldFish['GoldFish'/7480, l='MpServer', x=-404.50, y=63.00, z=-430.50], EntityItem['item.tile.flower_1.miners_delight'/6969, l='MpServer', x=-364.17, y=46.00, z=-488.04], MoCEntityBlackBear['BlackBear'/6970, l='MpServer', x=-325.50, y=74.00, z=-413.50], MoCEntityBlackBear['BlackBear'/6971, l='MpServer', x=-327.50, y=74.00, z=-413.50], MoCEntityBlackBear['BlackBear'/5190, l='MpServer', x=-270.76, y=74.00, z=-504.81], EntityCreeper['Creeper'/7238, l='MpServer', x=-281.50, y=64.00, z=-458.50], MoCEntityBlackBear['BlackBear'/5191, l='MpServer', x=-268.72, y=75.00, z=-506.04], MoCEntityBlackBear['BlackBear'/5192, l='MpServer', x=-379.50, y=63.00, z=-516.50], EntityItem['item.tile.flower_1.miners_delight'/6988, l='MpServer', x=-323.72, y=43.00, z=-451.48], EntityZombie['Zombie'/7245, l='MpServer', x=-376.80, y=49.00, z=-513.51], MoCEntityBlackBear['BlackBear'/6482, l='MpServer', x=-256.50, y=68.00, z=-454.50], MoCEntityGoat['Goat'/6483, l='MpServer', x=-269.22, y=64.00, z=-455.51], MoCEntityGoat['Goat'/6484, l='MpServer', x=-268.23, y=64.00, z=-459.49], EntitySkeleton['Skeleton'/6997, l='MpServer', x=-357.50, y=37.00, z=-488.50], EntityZombie['Zombie'/7516, l='MpServer', x=-337.50, y=37.00, z=-505.50], EntitySpider['Spider'/7517, l='MpServer', x=-336.50, y=37.00, z=-506.50], EntitySkeleton['Skeleton'/7008, l='MpServer', x=-372.50, y=43.00, z=-499.50], EntitySkeleton['Skeleton'/7523, l='MpServer', x=-301.50, y=38.00, z=-468.50], EntityItem['item.tile.doublePlant.syringa'/6501, l='MpServer', x=-342.78, y=73.00, z=-485.46], EntitySkeleton['Skeleton'/7525, l='MpServer', x=-373.50, y=39.00, z=-506.50], EntitySpider['Spider'/7021, l='MpServer', x=-310.50, y=11.00, z=-486.50], EntityZombie['Zombie'/7026, l='MpServer', x=-268.50, y=5.00, z=-506.50], EntitySquid['Squid'/7028, l='MpServer', x=-333.88, y=60.00, z=-498.38], MoCEntityWerewolf['Werewolf'/7035, l='MpServer', x=-308.44, y=33.00, z=-471.40], EntitySkeleton['Skeleton'/7053, l='MpServer', x=-263.50, y=76.00, z=-514.50], EntitySkeleton['Skeleton'/7054, l='MpServer', x=-263.50, y=76.00, z=-513.50], EntitySkeleton['Skeleton'/7567, l='MpServer', x=-348.50, y=42.00, z=-498.50], EntityZombieVillager['Zombie Villager'/7056, l='MpServer', x=-387.50, y=35.00, z=-487.50], EntityCreeper['Creeper'/6803, l='MpServer', x=-321.50, y=11.00, z=-531.50], EntitySkeleton['Skeleton'/7317, l='MpServer', x=-335.50, y=16.00, z=-478.50], EntitySkeleton['Skeleton'/7318, l='MpServer', x=-336.50, y=16.00, z=-477.50], EntityEnderman['Enderman'/7578, l='MpServer', x=-396.50, y=84.00, z=-454.50], EntityZombie['Zombie'/7323, l='MpServer', x=-343.50, y=39.00, z=-501.08], EntityCreeper['Creeper'/7579, l='MpServer', x=-302.50, y=11.00, z=-447.50], EntityCreeper['Creeper'/7581, l='MpServer', x=-298.83, y=47.11, z=-464.50], EntityEnderman['Enderman'/7582, l='MpServer', x=-293.50, y=45.00, z=-462.50], EntityEnderman['Enderman'/7583, l='MpServer', x=-293.50, y=45.00, z=-465.50], MoCEntityGoat['Goat'/7073, l='MpServer', x=-271.50, y=65.00, z=-390.50], MoCEntityGoat['Goat'/7074, l='MpServer', x=-271.50, y=66.00, z=-392.50], MoCEntityBird['Bird'/7075, l='MpServer', x=-358.69, y=85.13, z=-385.38], EntityZombie['Zombie'/7332, l='MpServer', x=-248.50, y=69.00, z=-465.50], EntityCreeper['Creeper'/7334, l='MpServer', x=-245.50, y=18.00, z=-449.50], EntityCreeper['Creeper'/7336, l='MpServer', x=-334.50, y=22.00, z=-465.50], MoCEntityBird['Bird'/7082, l='MpServer', x=-327.78, y=78.19, z=-419.60], MoCEntityBird['Bird'/7083, l='MpServer', x=-327.55, y=81.00, z=-381.35], MoCEntityBird['Bird'/7084, l='MpServer', x=-333.50, y=80.00, z=-386.50], EntitySheep['Sheep'/7085, l='MpServer', x=-343.50, y=77.00, z=-393.50], EntitySheep['Sheep'/7086, l='MpServer', x=-344.50, y=77.00, z=-394.50], EntitySheep['Sheep'/7087, l='MpServer', x=-344.50, y=77.00, z=-394.50], EntitySheep['Sheep'/7088, l='MpServer', x=-333.01, y=79.00, z=-397.10], MoCEntityBlackBear['BlackBear'/7089, l='MpServer', x=-280.50, y=64.00, z=-391.50], MoCEntityGoat['Goat'/7090, l='MpServer', x=-272.50, y=65.00, z=-391.50], EntityItem['item.tile.flower_0.white_anemone'/7093, l='MpServer', x=-311.62, y=63.00, z=-441.65], EntitySkeleton['Skeleton'/7094, l='MpServer', x=-343.50, y=6.00, z=-513.50], EntitySkeleton['Skeleton'/7096, l='MpServer', x=-352.50, y=39.00, z=-486.50], MoCEntityBlackBear['BlackBear'/5051, l='MpServer', x=-397.50, y=75.00, z=-529.50], EntityCreeper['Creeper'/7103, l='MpServer', x=-263.50, y=38.00, z=-456.50], EntitySkeleton['Skeleton'/7368, l='MpServer', x=-284.50, y=12.00, z=-432.50], EntityPlayerSP['XXXXXXXXXX'/1859, l='MpServer', x=-325.28, y=65.23, z=-452.54], EntityZombie['Zombie'/7369, l='MpServer', x=-285.50, y=12.00, z=-431.50], EntityZombie['Zombie'/7370, l='MpServer', x=-282.50, y=12.00, z=-431.50], MoCEntityBird['Bird'/7117, l='MpServer', x=-356.57, y=76.00, z=-379.48], MoCEntityBird['Bird'/7118, l='MpServer', x=-328.94, y=85.66, z=-382.60], EntitySkeleton['Skeleton'/7375, l='MpServer', x=-355.50, y=72.00, z=-415.50], MoCEntityBird['Bird'/7119, l='MpServer', x=-352.43, y=76.00, z=-376.20], MoCEntityBird['Bird'/7120, l='MpServer', x=-332.81, y=81.73, z=-387.71], MoCEntityBird['Bird'/7121, l='MpServer', x=-349.36, y=77.00, z=-373.26], MoCEntityBird['Bird'/7122, l='MpServer', x=-342.79, y=77.00, z=-381.27], MoCEntityBird['Bird'/7123, l='MpServer', x=-345.13, y=77.00, z=-382.84], EntitySkeleton['Skeleton'/6873, l='MpServer', x=-343.50, y=39.00, z=-500.30], EntityLatchedRenderer['unknown'/1502, l='MpServer', x=-325.07, y=65.54, z=-452.49], EntityItem['item.item.crystal_essence'/6888, l='MpServer', x=-332.82, y=16.00, z=-480.13], EntityZombie['Zombie'/7403, l='MpServer', x=-377.29, y=43.00, z=-458.50], EntitySpider['Spider'/7409, l='MpServer', x=-276.50, y=13.00, z=-408.50], EntityCreeper['Creeper'/7410, l='MpServer', x=-399.83, y=76.00, z=-480.54], EntitySkeleton['Skeleton'/7164, l='MpServer', x=-256.50, y=29.00, z=-452.50], MoCEntityBlackBear['BlackBear'/6908, l='MpServer', x=-288.24, y=63.00, z=-437.86]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ghost** [comment]
This crash happened for every aquatic animal.
With the following config i had no crashes anymore:
[https://pastebin.com/n26mPiJC](
https://pastebin.com/n26mPiJC)

**Comment by RedEpicness** [comment]
I have the same issue for most aquatic animals. Any idea on how to fix this without disabling stuff anyone?

**Comment by noobanidus** [comment]
I've noticed this issue also with Forge 2796. I'm not sure why the value of a DataParameter that is specifically defined as a boolean would be returning an integer, implying that there's some corruption along the way (hence the need to explicitly cast the result as a boolean). My solution for testing compatibility between this mod and my own (Dude! Where's my Horse?) was to use In Control to prevent any other monsters spawning except the ones I chose.

**Comment by rbroderi** [comment]
I have produced an updated MoCEntityTameableAquatic.class file which seems to bypass that error. I can't claim it solved the root cause but it should stop minecraft from crashing at the very least.
[MoCEntityTameableAquatic.class](https://filebin.net/b465cz6vwe9f3z8a)

Just open the DrZharks-MoCreatures-Mod-12.0.5.jar file with your favorite zip program (I used 7zip) and browse to drzhark\mocreatures\entity\ remove the existing MoCEntityTameableAquatic.class file and replace with the linked patched file.
