### ISSUE TITLE
Black Screen 1.12.2 (Problem solved)

### ISSUE THREAD

**Issue by Shiomari** [DrZhark/mocreatures#139]
Werewolf texture not visible
When a werewolf takes damage, the minecraft window becomes black, reacts to the buttons, but everything is black, including the menu.

Constantly duplicates this error:

[13:53:47] [Client thread/ERROR] [net.minecraft.client.renderer.entity.RenderLivingBase]: Couldn't render entity
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:95) ~[cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) ~[cdr.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:101) ~[bzg.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf$LayerMoCWereHuman.doRenderLayer(MoCRenderWerewolf.java:62) ~[MoCRenderWerewolf$LayerMoCWereHuman.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf$LayerMoCWereHuman.func_177141_a(MoCRenderWerewolf.java:38) ~[MoCRenderWerewolf$LayerMoCWereHuman.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:439) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:186) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41) [caf.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf.doRender(MoCRenderWerewolf.java:29) [MoCRenderWerewolf.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf.func_76986_a(MoCRenderWerewolf.java:15) [MoCRenderWerewolf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:61) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) ~[cdr.class:?]
	... 24 more
[13:53:48] [Client thread/ERROR] [net.minecraft.client.renderer.entity.RenderLivingBase]: Couldn't render entity
net.minecraft.util.ReportedException: Registering texture
[latest.log](https://github.com/DrZhark/mocreatures/files/3012789/latest.log)

**Comment by Shiomari** [comment]
Oh, I saw a comment on the previous issue, the problem is solved =D
Can I somehow delete this issue?

**Comment by googlepox** [comment]
How did you solve this? I can't find the previous issue you're referring to.

**Comment by Shiomari** [comment]
Rename mod file, "+" in name break mod
