### ISSUE TITLE
Crash on client for entity drzhark.mocreatures.entity.aquatic.MoCEntityCod

### ISSUE THREAD

**Issue by dotModded** [DrZhark/mocreatures#14]
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
  at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:83)
    at drzhark.mocreatures.entity.MoCEntityTameableAquatic.func_70094_T(MoCEntityTameableAquatic.java:424)
    at lycanite.lycanitesmobs.ExtendedEntity.onUpdate(ExtendedEntity.java:123)
    at lycanite.lycanitesmobs.EventListener.onEntityUpdate(EventListener.java:192)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_564_EventListener_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:491)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1937)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
    at net.minecraft.world.World.redirect$onCallEntityUpdate$zjk000(World.java:1044)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1211)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by dotModded** [comment]
I'm aware that this could be caused by lycanitesmobs however I'm reporting in both places
