### ISSUE TITLE
Werewolf causes black screen

### ISSUE THREAD

**Issue by BoatTK** [DrZhark/mocreatures#214]
Whenever a werewolf is rendered, it is invisible and the game suddenly black screens. The log says this several hundreds of times (So im assuming every tick):
[23:31:49] [Client thread/ERROR] [net.minecraft.client.renderer.entity.RenderLivingBase]: Couldn't render entity
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:95) ~[cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:44) ~[cdr.class:?]
	at net.minecraft.client.renderer.entity.Render.bindTexture(SourceFile:101) ~[bzg.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf$LayerMoCWereHuman.doRenderLayer(MoCRenderWerewolf.java:56) ~[MoCRenderWerewolf$LayerMoCWereHuman.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf$LayerMoCWereHuman.doRenderLayer(MoCRenderWerewolf.java:38) ~[MoCRenderWerewolf$LayerMoCWereHuman.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.renderLayers(RenderLivingBase.java:439) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.doRender(RenderLivingBase.java:186) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(SourceFile:41) [caf.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf.doRender(MoCRenderWerewolf.java:29) [MoCRenderWerewolf.class:?]
	at drzhark.mocreatures.client.renderer.entity.MoCRenderWerewolf.doRender(MoCRenderWerewolf.java:15) [MoCRenderWerewolf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:384) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:368) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.redirect$renderEntityStatic$zdd000(RenderGlobal.java:3137) [buy.class:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:628) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1347) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException

**Comment by Opalie** [comment]
Same issue, here is my entire log: https://drive.google.com/file/d/1fLilovVkt3k3jYpH8XPmIlLpLtOweQXm/view?usp=sharing
Sorry for the google drive link, pastebin was just not working for me today.

**Comment by BoatTK** [comment]
Sorry, forgot to mention. Another thread answered this problem. Basically, the modfile has "+"s between every word which somehow corrupts the werewolves. To fix this all you have to do is go into your mods folder and rename to mod.
