### ISSUE TITLE
The game crashed whilst ticking entity

### ISSUE THREAD

**Issue by Ghestal** [DrZhark/mocreatures#236]
I was flying around in the world when I got this crash below. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 4/28/21 1:22 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:89)
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.func_70094_T(MoCEntityTameableAquatic.java:452)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:232)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
	at drzhark.mocreatures.entity.MoCEntityAquatic.func_70030_z(MoCEntityAquatic.java:914)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2096)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:89)
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.func_70094_T(MoCEntityTameableAquatic.java:452)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:232)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
	at drzhark.mocreatures.entity.MoCEntityAquatic.func_70030_z(MoCEntityAquatic.java:914)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2096)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: mocreatures:salmon (drzhark.mocreatures.entity.aquatic.MoCEntitySalmon)
	Entity ID: 8389
	Entity Name: Salmon
	Entity's Exact location: 234.50, 64.00, 1415.50
	Entity's Block location: World: (234,64,1415), Chunk: (at 10,4,7 in 14,88; contains blocks 224,0,1408 to 239,255,1423), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ghestal'/2005, l='MpServer', x=184.33, y=64.12, z=1454.57]]
	Chunk stats: MultiplayerChunkCache: 574, 574
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2400 game time, 2400 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 93 total; [EntityMinecartChest['Minecart with Chest'/7937, l='MpServer', x=119.50, y=40.06, z=1522.50], EntityCreeper['Creeper'/8197, l='MpServer', x=260.50, y=34.00, z=1376.50], EntityCreeper['Creeper'/8198, l='MpServer', x=260.50, y=34.00, z=1374.50], EntityCreeper['Creeper'/8200, l='MpServer', x=179.50, y=14.00, z=1436.50], EntityZombie['Zombie'/8213, l='MpServer', x=228.50, y=32.00, z=1398.50], EntitySkeleton['Skeleton'/8214, l='MpServer', x=185.50, y=12.00, z=1428.50], EntitySkeleton['Skeleton'/8215, l='MpServer', x=187.50, y=12.00, z=1428.50], MoCEntitySilverSkeleton['SilverSkeleton'/8216, l='MpServer', x=182.50, y=12.00, z=1427.50], EntityItem['item.tile.torch'/7449, l='MpServer', x=163.87, y=16.00, z=1414.84], MoCEntitySilverSkeleton['SilverSkeleton'/8217, l='MpServer', x=185.50, y=12.00, z=1426.50], MoCEntityKomodo['KomodoDragon'/7450, l='MpServer', x=239.50, y=66.00, z=1403.50], MoCEntityKomodo['KomodoDragon'/7451, l='MpServer', x=235.50, y=67.00, z=1401.50], EntityZombie['Zombie'/8231, l='MpServer', x=177.50, y=15.00, z=1394.50], EntityCreeper['Creeper'/8232, l='MpServer', x=175.50, y=15.00, z=1397.50], EntityItem['item.tile.mushroom1'/7722, l='MpServer', x=160.70, y=13.00, z=1418.43], EntityItem['item.tile.flower_1.miners_delight'/7723, l='MpServer', x=148.35, y=13.00, z=1409.31], EntityZombie['Zombie'/7980, l='MpServer', x=184.50, y=18.00, z=1400.50], EntitySkeleton['Skeleton'/8240, l='MpServer', x=238.50, y=15.00, z=1458.50], EntityItem['item.tile.rail'/7985, l='MpServer', x=157.28, y=14.00, z=1468.13], EntityPlayerSP['Ghestal'/2005, l='MpServer', x=184.33, y=64.12, z=1454.57], EntityCreeper['Creeper'/7996, l='MpServer', x=221.50, y=18.00, z=1378.50], EntityCreeper['Creeper'/7997, l='MpServer', x=225.50, y=33.00, z=1377.50], EntityCreeper['Creeper'/7998, l='MpServer', x=224.50, y=33.00, z=1377.50], EntityZombie['Zombie'/8255, l='MpServer', x=176.50, y=13.00, z=1430.50], EntityCreeper['Creeper'/8256, l='MpServer', x=177.50, y=13.00, z=1429.50], EntityCreeper['Creeper'/8257, l='MpServer', x=178.50, y=13.00, z=1426.50], EntityCreeper['Creeper'/8258, l='MpServer', x=178.50, y=13.00, z=1428.50], EntityZombie['Zombie'/8259, l='MpServer', x=245.50, y=43.00, z=1406.50], EntityItem['item.tile.rail'/7751, l='MpServer', x=149.30, y=13.00, z=1408.78], EntityEnderman['Enderman'/8020, l='MpServer', x=220.50, y=35.00, z=1403.50], EntityEnderman['Enderman'/8021, l='MpServer', x=219.50, y=35.00, z=1403.50], MoCEntityHorseMob['HorseMob'/8022, l='MpServer', x=209.70, y=31.89, z=1395.80], MoCEntityHorseMob['HorseMob'/8023, l='MpServer', x=221.30, y=37.09, z=1400.06], EntityZombie['Zombie'/8279, l='MpServer', x=238.50, y=13.00, z=1373.50], EntityZombie['Zombie'/8282, l='MpServer', x=239.50, y=13.00, z=1371.50], EntityItem['item.tile.rail'/7771, l='MpServer', x=154.79, y=13.00, z=1413.58], EntityZombie['Zombie'/8284, l='MpServer', x=251.70, y=42.18, z=1433.73], EntityItem['item.item.reptilehide'/8286, l='MpServer', x=156.56, y=62.88, z=1439.81], EntityItem['item.tile.rail'/8289, l='MpServer', x=158.27, y=14.00, z=1443.18], EntityItem['item.tile.rail'/8044, l='MpServer', x=158.43, y=14.00, z=1463.14], EntityCreeper['Creeper'/8304, l='MpServer', x=204.82, y=54.00, z=1435.40], EntityCreeper['Creeper'/8305, l='MpServer', x=206.50, y=53.00, z=1434.50], EntitySkeleton['Skeleton'/8309, l='MpServer', x=202.50, y=17.00, z=1431.50], EntitySkeleton['Skeleton'/8057, l='MpServer', x=242.50, y=41.00, z=1405.50], EntitySkeleton['Skeleton'/8058, l='MpServer', x=243.50, y=41.00, z=1405.50], EntitySkeleton['Skeleton'/8059, l='MpServer', x=243.50, y=41.00, z=1402.50], EntitySkeleton['Skeleton'/8060, l='MpServer', x=244.50, y=41.00, z=1403.50], EntityItem['item.tile.torch'/7551, l='MpServer', x=205.88, y=12.00, z=1427.85], EntityItem['item.tile.torch'/7552, l='MpServer', x=193.49, y=14.00, z=1417.57], MoCEntityKomodo['KomodoDragon'/7553, l='MpServer', x=191.50, y=62.88, z=1427.50], MoCEntityKomodo['KomodoDragon'/7554, l='MpServer', x=190.50, y=62.88, z=1425.50], EntitySkeleton['Skeleton'/8324, l='MpServer', x=176.50, y=32.00, z=1450.50], EntityMinecartChest['Minecart with Chest'/7558, l='MpServer', x=146.50, y=14.06, z=1431.50], EntityItem['item.tile.torch'/7814, l='MpServer', x=170.33, y=15.00, z=1467.13], EntityZombie['Zombie'/8327, l='MpServer', x=222.50, y=49.00, z=1412.50], EntitySkeleton['Skeleton'/8329, l='MpServer', x=212.50, y=54.00, z=1379.50], EntitySkeleton['Skeleton'/8330, l='MpServer', x=211.50, y=54.00, z=1380.50], EntityItem['item.tile.rail'/8331, l='MpServer', x=138.67, y=41.00, z=1475.82], EntitySkeleton['Skeleton'/8333, l='MpServer', x=179.50, y=49.00, z=1485.50], EntityZombieVillager['Zombie Villager'/8078, l='MpServer', x=201.82, y=14.00, z=1380.50], EntityItem['item.tile.rail'/8334, l='MpServer', x=138.75, y=41.00, z=1475.24], EntityItem['item.tile.rail'/8083, l='MpServer', x=157.66, y=14.00, z=1459.61], EntityItem['item.tile.rail'/8345, l='MpServer', x=137.65, y=41.68, z=1476.16], EntityItem['item.tile.torch'/7326, l='MpServer', x=201.51, y=14.00, z=1390.86], MoCEntityKomodo['KomodoDragon'/7328, l='MpServer', x=205.52, y=63.88, z=1395.56], EntityItem['item.tile.mushroom.glowshroom'/7845, l='MpServer', x=221.13, y=37.00, z=1468.75], EntityZombie['Zombie'/8105, l='MpServer', x=239.50, y=14.00, z=1373.50], EntityZombie['Zombie'/8106, l='MpServer', x=244.50, y=14.00, z=1376.50], EntityZombie['Zombie'/8107, l='MpServer', x=240.50, y=14.00, z=1376.50], EntityZombieVillager['Zombie Villager'/8108, l='MpServer', x=242.50, y=14.00, z=1377.50], EntitySpider['Spider'/8366, l='MpServer', x=231.50, y=39.00, z=1416.50], EntityItem['item.tile.rail'/8367, l='MpServer', x=136.59, y=41.00, z=1475.13], EntityItem['item.tile.rail'/8368, l='MpServer', x=135.08, y=41.00, z=1476.41], EntityItem['item.tile.rail'/8370, l='MpServer', x=134.37, y=41.27, z=1477.45], EntityItem['item.tile.mushroom.glowshroom'/7859, l='MpServer', x=220.88, y=36.00, z=1476.14], EntityItem['item.tile.torch'/7860, l='MpServer', x=138.43, y=42.00, z=1485.08], EntityItem['item.tile.torch'/7862, l='MpServer', x=128.56, y=36.00, z=1487.13], EntityItem['item.tile.flower_1.miners_delight'/7609, l='MpServer', x=148.29, y=13.00, z=1413.65], EntityCreeper['Creeper'/8387, l='MpServer', x=226.50, y=23.00, z=1403.50], EntityItem['item.tile.rail'/8388, l='MpServer', x=134.51, y=42.07, z=1476.51], EntityItem['item.item.reptilehide'/8133, l='MpServer', x=202.16, y=62.88, z=1393.88], MoCEntitySalmon['Salmon'/8389, l='MpServer', x=234.50, y=64.00, z=1415.50], MoCEntityGoldFish['GoldFish'/8390, l='MpServer', x=150.50, y=16.00, z=1452.50], EntityItem['item.tile.rail'/7623, l='MpServer', x=148.83, y=13.00, z=1412.54], MoCEntityDolphin['Dolphin'/8391, l='MpServer', x=151.50, y=16.00, z=1450.50], EntityItem['item.tile.flower_1.miners_delight'/7624, l='MpServer', x=145.13, y=13.00, z=1418.08], MoCEntityKomodo['KomodoDragon'/7632, l='MpServer', x=111.50, y=63.00, z=1440.50], EntityItem['item.tile.torch'/7897, l='MpServer', x=136.66, y=40.00, z=1501.06], EntityZombie['Zombie'/8155, l='MpServer', x=218.50, y=55.00, z=1436.50], EntitySkeleton['Skeleton'/8156, l='MpServer', x=246.50, y=53.00, z=1424.50], EntityMinecartChest['Minecart with Chest'/7900, l='MpServer', x=156.50, y=37.06, z=1511.50], EntityCreeper['Creeper'/7932, l='MpServer', x=143.50, y=12.00, z=1379.50], EntityCreeper['Creeper'/7934, l='MpServer', x=142.50, y=12.00, z=1376.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1985733448 bytes (1893 MB) / 6509559808 bytes (6208 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 68 mods loaded, 68 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version            | Source                                              | Signature                                |
	|:------ |:--------------------------------- |:------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2             | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                               | 9.42               | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                               | 8.0.99.99          | forge-1.12.2-14.23.5.2855.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2855       | forge-1.12.2-14.23.5.2855.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | antiqueatlas                      | 4.6.3              | antiqueatlas-1.12.2-4.6.3.jar                       | None                                     |
	| LCHIJA | antiqueatlasoverlay               | 1.2                | antiqueatlas-1.12.2-4.6.3.jar                       | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-7       | appliedenergistics2-rv6-stable-7.jar                | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | aquaculture                       | 1.6.8              | Aquaculture-1.12.2-1.6.8.jar                        | None                                     |
	| LCHIJA | battletowers                      | 1.6.5              | BattleTowers-1.12.2.jar                             | None                                     |
	| LCHIJA | baubles                           | 1.5.2              | Baubles-1.12-1.5.2.jar                              | None                                     |
	| LCHIJA | bibliocraft                       | 2.4.5              | BiblioCraft[v2.4.5][MC1.12.2].jar                   | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2444         | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar       | None                                     |
	| LCHIJA | guideapi                          | 1.12-2.1.8-63      | Guide-API-1.12-2.1.8-63.jar                         | None                                     |
	| LCHIJA | bloodmagic                        | 1.12.2-2.4.3-105   | BloodMagic-1.12.2-2.4.3-105.jar                     | None                                     |
	| LCHIJA | bloodmoon                         | 1.5.3              | Bloodmoon-MC1.12.2-1.5.3.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | thaumcraft                        | 6.1.BETA26         | Thaumcraft-1.12.2-6.1.BETA26.jar                    | None                                     |
	| LCHIJA | botania                           | r1.10-363          | Botania+r1.10-363.jar                               | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.3.358          | CodeChickenLib-1.12.2-3.2.3.358-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.1              | RedstoneFlux-1.12-2.1.1.1-universal.jar             | None                                     |
	| LCHIJA | brandonscore                      | 2.4.19             | BrandonsCore-1.12.2-2.4.19.214-universal.jar        | None                                     |
	| LCHIJA | chickenchunks                     | 2.4.2.74           | ChickenChunks-1.12.2-2.4.2.74-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | geckolib3                         | 3.0.0              | forge-1.12.2-geckolib-3.0.0-beta.7.jar              | None                                     |
	| LCHIJA | cqrepoured                        | 2.4.3B             | Chocolate_Quest_Repoured-1.12.2-2.4.3B.jar          | None                                     |
	| LCHIJA | computercraft                     | 1.80pr1            | ComputerCraft1.80pr1.jar                            | None                                     |
	| LCHIJA | extendedrenderer                  | v1.0               | coroutil-1.12.1-1.2.37.jar                          | None                                     |
	| LCHIJA | coroutil                          | 1.12.1-1.2.37      | coroutil-1.12.1-1.2.37.jar                          | None                                     |
	| LCHIJA | configmod                         | v1.0               | coroutil-1.12.1-1.2.37.jar                          | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.27             | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar  | None                                     |
	| LCHIJA | mocreatures                       | 12.0.5             | DrZharks Mocreatures Mod-12.0.5.jar                 | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76      | EnderCore-1.12.2-0.5.76.jar                         | None                                     |
	| LCHIJA | enderio                           | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderiobase                       | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55      | Mantle-1.12-1.3.3.55.jar                            | None                                     |
	| LCHIJA | twilightforest                    | 3.11.1021          | twilightforest-1.12.2-3.11.1021-universal.jar       | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183  | TConstruct-1.12.2-2.13.0.183.jar                    | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.66             | EnderIO-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | zerocore                          | 1.12.2-0.1.2.9     | zerocore-1.12.2-0.1.2.9.jar                         | None                                     |
	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.68    | ExtremeReactors-1.12.2-0.4.5.68.jar                 | None                                     |
	| LCHIJA | fairylights                       | 2.1.10             | fairylights-2.2.0-1.12.2.jar                        | None                                     |
	| LCHIJA | hardcoredarkness                  | 2.0                | HardcoreDarkness-MC1.12.2-2.0.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | infernalmobs                      | 1.7.6              | InfernalMobs-1.12.2.jar                             | None                                     |
	| LCHIJA | kinetic anti-cheat                | 12.2.2             | kinetic_anti-cheat-12.2.2.jar                       | None                                     |
	| LCHIJA | mcwdoors                          | 1.0                | mcw-doors-1.0.0-mc1.12.2.jar                        | None                                     |
	| LCHIJA | mcwroofs                          | 1.0.2              | mcw-roofs-1.0.2-mc1.12.2.jar                        | None                                     |
	| LCHIJA | mcwtrpdoors                       | 1.0.2              | mcw-trapdoors-1.0.2-mc1.12.2.jar                    | None                                     |
	| LCHIJA | mcwwindows                        | 1.0                | mcw-windows-1.0.0-mc1.12.2.jar                      | None                                     |
	| LCHIJA | llibrary                          | 1.7.20             | llibrary-1.7.20-1.12.2.jar                          | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs                       | 1.5.8              | mowziesmobs-1.5.8.jar                               | None                                     |
	| LCHIJA | harvestcraft                      | 1.12.2zb           | Pam's+HarvestCraft+1.12.2zg.jar                     | None                                     |
	| LCHIJA | peacefulsurface                   | 1.12.2-v2          | PeacefulSurface-1.12.2-v2.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | pneumaticcraft                    | 1.12.2-0.11.15-398 | pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar | None                                     |
	| LCHIJA | progressivebosses                 | 1.5.4              | ProgressiveBosses-1.5.4-mc1.12.x.jar                | None                                     |
	| LCHIJA | rsgauges                          | 1.2.5              | rsgauges-1.12.2-1.2.5.jar                           | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | immersiveengineering              | 0.12-98            | ImmersiveEngineering-0.12-98.jar                    | None                                     |
	| LCHIJA | simplyjetpacks                    | 1.12.2-2.2.19.0    | SimplyJetpacks2-1.12.2-2.2.19.0.jar                 | None                                     |
	| LCHIJA | spartanshields                    | 1.5.4              | SpartanShields-1.12.2-1.5.4.jar                     | None                                     |
	| LCHIJA | treechopper                       | 1.2.4              | TreeChopper-1.12.2-1.2.4.jar                        | None                                     |
	| LCHIJA | vc                                | 5.9.16             | ViesCraft-1.12.2-5.9.16.jar                         | None                                     |
	| LCHIJA | weather2                          | 1.12.1-2.6.12      | weather2-1.12.1-2.6.12.jar                          | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.11' Renderer: 'NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/Matt/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.11, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 466.11
	OpenGlRenderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by I-Knight-I** [comment]
Yup, having this as well.

**Comment by pehage** [comment]
Having the same one, but with the enitity HippoTang
