### ISSUE TITLE
Fish on land and Dolphins

### ISSUE THREAD

**Issue by ghost** [DrZhark/mocreatures#3]
Forge: 2107
MC: 1.10.2
Mo Creatures: 10.0.4

A lot of fish seem to be spawning and dying on land. Im in a Biomes of plenty Dead Swamp biome

Also got the following error when I was mining close to sea

Sorry to be a nuissance.

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
    at drzhark.mocreatures.entity.MoCEntityAquatic.getPetName(MoCEntityAquatic.java:137)
    at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.doRender(MoCRenderDolphin.java:26)
    at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.func_76986_a(MoCRenderDolphin.java:16)
    at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:397)
    at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:374)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:804)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at drzhark.mocreatures.entity.MoCEntityAquatic.getPetName(MoCEntityAquatic.java:137)
    at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.doRender(MoCRenderDolphin.java:26)
    at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.func_76986_a(MoCRenderDolphin.java:16)

-- Entity being rendered --
Details:
    Entity Type: mocreatures.Dolphin (drzhark.mocreatures.entity.aquatic.MoCEntityDolphin)
    Entity ID: 51548
    Entity Name: Dolphin
    Entity's Exact location: 1673.78, 58.10, 2996.69
    Entity's Block location: World: (1673,58,2996), Chunk: (at 9,3,4 in 104,187; contains blocks 1664,0,2992 to 1679,255,3007), Region: (3,5; contains chunks 96,160 to 127,191, blocks 1536,0,2560 to 2047,255,3071)
    Entity's Momentum: 0.00, -0.01, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
    Assigned renderer: drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin@7727f23f
    Location: 76.26,-6.90,71.27 - World: (76,-7,71), Chunk: (at 12,-1,7 in 4,4; contains blocks 64,0,64 to 79,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Rotation: -126.5625
    Delta: 0.25101757
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:397)
    at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:374)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:804)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

**Comment by DrZhark** [comment]
please check the other thread

**Comment by Luminatron** [comment]
What other thread? Where?? How the hecc do you redirect without giving a link

**Comment by MagmaSlime123** [comment]
> please check the other thread

You have 200+ issues. Fix them.
