### ISSUE TITLE
Mod incompatibility with mod Quark

### ISSUE THREAD

**Issue by Alrawn** [DrZhark/mocreatures#31]
This looks like some incompatibility problem to me, but I'm unsure as to who needs to fix what:

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockStateContainer{block=quark:stone_basalt_bricks_slab_double, properties=[prop]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at drzhark.customspawner.CustomSpawner.canCreatureSpawn(CustomSpawner.java:606)
	at drzhark.customspawner.CustomSpawner.canCreatureTypeSpawnAtLocation(CustomSpawner.java:590)
	at drzhark.customspawner.CustomSpawner.doCustomSpawning(CustomSpawner.java:309)
	at drzhark.customspawner.handlers.SpawnTickHandler.worldTick(SpawnTickHandler.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_849_SpawnTickHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Palpiter** [comment]
For reference:
https://github.com/Vazkii/Quark/issues/200

**Comment by frakier** [comment]
CMS does not seem to have problems with other slabs, just quark. I would just take out CMS in favor of something if there was something else that I can use to control mob spawns. JAS seems dead I downloaded the code and updated it to 1.10.2  but could not fix creatures spawning half in blocks. May try turning off quarks half-slabs and see if a possible further error could point to a solution.
