### ISSUE TITLE
[crash log][1.10.2] dolphin crashed the game??

### ISSUE THREAD

**Issue by winsrp** [DrZhark/mocreatures#32]
Well, here is the error log... dang those dolphins!

`Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at drzhark.mocreatures.entity.MoCEntityAquatic.getPetName(MoCEntityAquatic.java:151)
	at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.doRender(MoCRenderDolphin.java:26)
	at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.func_76986_a(MoCRenderDolphin.java:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at drzhark.mocreatures.entity.MoCEntityAquatic.getPetName(MoCEntityAquatic.java:151)
	at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.doRender(MoCRenderDolphin.java:26)
	at drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin.func_76986_a(MoCRenderDolphin.java:16)

-- Entity being rendered --
Details:
	Entity Type: mocreatures.Dolphin (drzhark.mocreatures.entity.aquatic.MoCEntityDolphin)
	Entity ID: 317
	Entity Name: Dolphin
	Entity's Exact location: 95.50, 63.00, 728.50
	Entity's Block location: World: (95,63,728), Chunk: (at 15,3,8 in 5,45; contains blocks 80,0,720 to 95,255,735), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -2.17, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: drzhark.mocreatures.client.renderer.entity.MoCRenderDolphin@709e128
	Location: 102.85,-59.00,14.41 - World: (102,-59,14), Chunk: (at 6,-4,14 in 6,0; contains blocks 96,0,0 to 111,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 35.15625
	Delta: 0.3972819
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)`

**Comment by Frigolit** [comment]
Running a single player game open to LAN, it crashes my girlfriend's game but not mine. Both Dolphin and Fishy have been the sources of error. Unfortunately it seems like Fishy still spawns even though I've disabled it in the config.

It's been months since this game breaking bug was raised. Have you ever considered open-sourcing the mod so others can contribute with bug fixes?

**Comment by TomberWolf** [comment]
Same crash here

**Comment by Iiridayn** [comment]
Yep, dolphin crash... Workaround/mitigation?

**Comment by Iiridayn** [comment]
In server console: `kill @e[type=mocreatures.Dolphin]`, then change the config to disable spawning them

**Comment by Iiridayn** [comment]
Hmm, changing the config file still spawns them :/. Still, workaround is to kill them from the server console when your players report client side crashes :(.

Edit: another one immediately spawned. This is not tenable :/.
Another edit: and again, setting all numbers in `config/MoCreatures/MoCreatures.cfg` dolphin section to 0 - `B:canspawn` was already `false` from my last attempted fix.

**Comment by Iiridayn** [comment]
Now jellyfish are crashing the client, seems the same, casting to string.
