### ISSUE TITLE
Crash when loading world (creating world crashes too)

### ISSUE THREAD

**Issue by GordonHollow** [DrZhark/mocreatures#35]
Minecraft 1.10.2
Forge 2122
MoCreatures and CustomMobSpawner last versions

PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at drzhark.customspawner.EventHooks.onLivingDespawn(EventHooks.java:142)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_385_EventHooks_onLivingDespawn_AllowDespawn.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.canEntityDespawn(ForgeEventFactory.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.call(Reflector.java:471)
	at net.minecraft.entity.EntityLiving.func_70623_bb(EntityLiving.java:847)
	at net.minecraft.entity.EntityLiving.onUpdateMinimal(EntityLiving.java:1682)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:379)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by GordonHollow** [comment]
On previous version of MoCreatures all works good
