### ISSUE TITLE
Game Crash in MoCEntityTameableAquatic

### ISSUE THREAD

**Issue by Tommsy64** [DrZhark/mocreatures#44]
My game crashed when entering the world. Seems to be an easy fix:
```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
```
Log [here](https://pastebin.com/a4svVBLc).

**Comment by thanatos** [comment]
I think I'm also experiencing this crash. Also when entering the world, same `ClassCastException`, same line. [My crash report](https://gist.github.com/thanatos/265ee9998793b104ad21efc23f6f421b).

**Comment by thanatos** [comment]
Same as #39?

**Comment by thanatos** [comment]
We killed a nearby dolphin (on the hunch of the crash being in `MoCEntityTameableAquatic.java`) on the server, and then the other person, who was on a client, was able to get in.

So I can remember: MoCreature's entities look like this in a kill command `kill @e[type=mocreatures.Salmon]`

**Comment by JohnLouderback** [comment]
I'm having this issue as well, but it appears to be with any aquatic mob. Crashes my game pretty quickly and consistently.
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:89)
	at drzhark.mocreatures.entity.MoCEntityTameableAquatic.func_70094_T(MoCEntityTameableAquatic.java:442)
```
```
-- Entity being ticked --
Details:
	Entity Type: mocreatures:fishy (drzhark.mocreatures.entity.aquatic.MoCEntityFishy)
	Entity ID: 5737
	Entity Name: Fishy
	Entity's Exact location: -661.50, 65.00, -409.50
	Entity's Block location: World: (-662,65,-410), Chunk: (at 10,4,6 in -42,-26; contains blocks -672,0,-416 to -657,255,-401), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
```

**Comment by Robijnvogel** [comment]
Since it doesn't seem like DrZhark will publish a fix for this soon, I have temporarily patched this by disabling the spawning of any entity that extends `MoCEntityTameableAquatic` using BiomeTweaker.

The content of my BT script is as follows:
```java
allBiomes = forAllBiomes()

allBiomes.removeSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityDolphin", "WATER_CREATURE")
allBiomes.removeSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityFishy", "WATER_CREATURE")
allBiomes.removeSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityJellyFish", "WATER_CREATURE")
allBiomes.removeSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityMediumFish", "WATER_CREATURE")
allBiomes.removeSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityRay", "WATER_CREATURE")
allBiomes.removeSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityShark", "WATER_CREATURE")
allBiomes.removeSpawn("drzhark.mocreatures.entity.aquatic.MoCEntitySmallFish", "WATER_CREATURE")```

**Comment by Leonature26** [comment]
tried disabling the spawns in config but no luck the fish are still ticking and crashing
i tried turning off sponge's option
(Caches tameable entities owners to avoid constant lookups against data watchers. If mods cause issues, disable this.
    cache-tameable-owners=false)
no crashing error so far even with fishes spawning

**Comment by Pdan4** [comment]
Same bug. [Log](https://paste.dimdev.org/xubemidece.mccrash)

Unfortunately BiomeTweaker also seems to crash.

**Comment by sineadTL** [comment]
Same bug, [log](https://hastebin.com/ewejayisiz.coffeescript)

Has anyone found a workaround?

**Comment by rbroderi** [comment]
Edit: 
I found that the fix didn't completely resolve issue reposting a newer version of fix

I have produced an updated MoCEntityTameableAquatic.class file which seems to bypass that error. I can't claim it solved the root cause but it should stop minecraft from crashing at the very least.
[MoCEntityTameableAquatic-fix3.0.zip](https://github.com/DrZhark/mocreatures/files/4483738/MoCEntityTameableAquatic-fix3.0.zip)



Just open the DrZharks-MoCreatures-Mod-12.0.5.jar file with your favorite zip program (I used 7zip) and browse to drzhark\mocreatures\entity\ remove the existing MoCEntityTameableAquatic.class file and replace with the linked patched file.

**Comment by Robijnvogel** [comment]
> 
> 
> Same bug. [Log](https://paste.dimdev.org/xubemidece.mccrash)
> 
> Unfortunately BiomeTweaker also seems to crash.

Well, the script only prevents further aquatic mobs from spawning. So those that have already spawned in a pre-existing world may still cause crashes. There are some mods that let you kill/force-despawn entities that may help in this case. Or you could start a new world.

> 
> 
> Same bug, [log](https://hastebin.com/ewejayisiz.coffeescript)
> 
> Has anyone found a workaround?

I have received recent confirmation that my fix still works. And then there is the previous reply to this issue that I am curious about. ;)

**Comment by sineadTL** [comment]
> I have received recent confirmation that my fix still works. And then there is the previous reply to this issue that I am curious about. ;)

Thanks, having success with your fix so far! I'd been hoping to find one that would allow our tamed dolphin to continue to exist so hadn't tried it till recently.

The patched file linked above seemed to be corrupted for me when unzipping so I haven't been able to try that out.

**Comment by Apemon7** [comment]
Bump

**Comment by ciqven** [comment]
I just received the same error, on a jar patched with the class @rbroderi posted above:

`[17:35:06] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at drzhark.mocreatures.entity.aquatic.MoCEntityJellyFish.func_184202_aL(MoCEntityJellyFish.java:58) ~[MoCEntityJellyFish.class:?]
        at net.minecraft.client.renderer.RenderGlobal.func_184383_a(RenderGlobal.java:1129) ~[buy.class:?]
        at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:853) ~[buy.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801) ~[buq.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614) ~[buq.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385) ~[buq.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:35:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
`
Is there a repo for MoCreatures somewhere so I can make a pull request to fix this?

**Comment by ghost** [comment]
> 
> 
> I just received the same error, on a jar patched with the class @rbroderi posted above:
> 
> `[17:35:06] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown! java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean at drzhark.mocreatures.entity.aquatic.MoCEntityJellyFish.func_184202_aL(MoCEntityJellyFish.java:58) ~[MoCEntityJellyFish.class:?] at net.minecraft.client.renderer.RenderGlobal.func_184383_a(RenderGlobal.java:1129) ~[buy.class:?] at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:853) ~[buy.class:?] at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801) ~[buq.class:?] at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614) ~[buq.class:?] at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385) ~[buq.class:?] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?] at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191] at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?] at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] [17:35:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ---- `
> Is there a repo for MoCreatures somewhere so I can make a pull request to fix this?

'func_184202_aL' on a deobfs is 'isGlowing'
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
    at drzhark.mocreatures.entity.aquatic.MoCEntityJellyFish.isGlowing(MoCEntityJellyFish.java:58)
    at net.minecraft.client.renderer.RenderGlobal.isOutlineActive(RenderGlobal.java:1128)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:854)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1808)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1621)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1390)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3442)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by RanLazarus** [comment]
> Edit:
> I found that the fix didn't completely resolve issue reposting a newer version of fix
> 
> I have produced an updated MoCEntityTameableAquatic.class file which seems to bypass that error. I can't claim it solved the root cause but it should stop minecraft from crashing at the very least.
> [MoCEntityTameableAquatic-fix3.0.zip](https://github.com/DrZhark/mocreatures/files/4483738/MoCEntityTameableAquatic-fix3.0.zip)
> 
> Just open the DrZharks-MoCreatures-Mod-12.0.5.jar file with your favorite zip program (I used 7zip) and browse to drzhark\mocreatures\entity\ remove the existing MoCEntityTameableAquatic.class file and replace with the linked patched file.

Thank you, this worked!          (Searching for an hour, 19mins to finally find a wonderful person who made a fix)

**Comment by ghost** [comment]
After doing some digging into this, it does seem that Jellyfishes will also cause crashes.
This isn't a issue with the patch though. It works fine.

I have a patched .class file, (fixing the issue relating to Jellyfish.isGlowing) but I cannot upload it for some reason.
Might try again later in the day if anyone requests me to make a dropbox or something.

change the `drzhark.mocreatures.entity.aquatic.MoCEntityJellyFish.isGlowing` file, on line 58.

**Comment by FullMetalMaster** [comment]
renaming the mod may also work just take out the Dzname part

**Comment by Xrelgamix** [comment]
Friends, at least in my case the problem with aquatic entities was due to the fact that I had not installed the "CustomMobSpawner" library, which was one of the ones that came with Mo Creatures, when I installed it I stopped crashing
I leave you the link that takes it from a page that had servers with this mod: http://www.mediafire.com/file/48n1ixz8i2belv2/CustomMobSpawner-3.11.4.jar/file

**Comment by jjw123** [comment]
> Edit: I found that the fix didn't completely resolve issue reposting a newer version of fix
> 
> I have produced an updated MoCEntityTameableAquatic.class file which seems to bypass that error. I can't claim it solved the root cause but it should stop minecraft from crashing at the very least. [MoCEntityTameableAquatic-fix3.0.zip](https://github.com/DrZhark/mocreatures/files/4483738/MoCEntityTameableAquatic-fix3.0.zip)
> 
> Just open the DrZharks-MoCreatures-Mod-12.0.5.jar file with your favorite zip program (I used 7zip) and browse to drzhark\mocreatures\entity\ remove the existing MoCEntityTameableAquatic.class file and replace with the linked patched file.

Wish I'd seen this before. I did a very similar thing myself earlier today.

I had another issue though which after testing it yours has the same problem. The aquatic mobs are no longer tameable. Because it assumes that numbers != 0 are untamed, when it returns the wrong value (I added a println to the bytecode and it's giving numbers around 100-160) the animals can never be tamed.

Obviously it's not as big of an issue as the crash, but I'm struggling to figure out what's wrong!

**Comment by TheGMan1776** [comment]
> After doing some digging into this, it does seem that Jellyfishes will also cause crashes. This isn't a issue with the patch though. It works fine.
> 
> I have a patched .class file, (fixing the issue relating to Jellyfish.isGlowing) but I cannot upload it for some reason. Might try again later in the day if anyone requests me to make a dropbox or something.
> 
> change the `drzhark.mocreatures.entity.aquatic.MoCEntityJellyFish.isGlowing` file, on line 58.

Where do I do this? What file? Also when I try to open one of the class files with 7Zip it doesn't work. Would you be able to upload the file somewhere? What am I supposed to edit it to?
